version = 1

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "browser"
  ]
  plugins = ["angular"]
  dialect = "typescript"
  style_guide = "airbnb"